version: '3.9'

services:
  database:
    extends:
      file: docker-compose.yml
      service: database
    volumes:
      - postgres-data:/var/lib/postgresql/data

  vector:
    extends:
      file: docker-compose.yml
      service: vector

  migrator:
    extends:
      file: docker-compose.yml
      service: migrator
    depends_on:
      - database
    pull_policy: always

  caddy:
    extends:
      file: docker-compose.yml
      service: caddy

  api:
    extends:
      file: docker-compose.yml
      service: api
    depends_on:
      database:
      migrator:
        condition: service_completed_successfully
    pull_policy: always

  www:
    extends:
      file: docker-compose.yml
      service: www
    pull_policy: always

volumes:
  postgres-data:
