version: '3.9'

services:
  database:
    image: postgres:15
    container_name: hhai-dev-pg
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  vector:
    image: timberio/vector:0.36.1-distroless-libc
    container_name: hhai-dev-vector
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: --config /etc/vector/vector.toml

  caddy:
    image: caddy:2
    container_name: hhai-dev-caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./.mount/www:/www
      - ./.mount/caddy-data/data:/data
      - ./.mount/caddy-data/config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"

  migrator:
    image: ghcr.io/wonrax/hhai-dev-migrator:latest
    container_name: hhai-dev-migrator
    build:
      context: ..
      dockerfile: docker/hhai-dev-migrator.Dockerfile
    env_file:
      - ../.env

  api:
    image: ghcr.io/wonrax/hhai-dev-api:latest
    container_name: hhai-dev-api
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/hhai-dev-api.Dockerfile
    env_file:
      - ../.env

  www:
    image: ghcr.io/wonrax/hhai-dev-www:latest
    container_name: hhai-dev-www
    build:
      context: ..
      dockerfile: docker/hhai-dev-www.Dockerfile
    volumes:
      - ./.mount/www/hhai.dev:/.mount
