version: '3.1'

services:
  database:
    extends:
      file: docker-compose.yml
      service: database

  log:
    extends:
      file: docker-compose.yml
      service: log

  migrator:
    extends:
      file: docker-compose.yml
      service: migrator
    depends_on:
      - database

  # Draft
  # api:
  #   depends_on:
  #     migrator:
  #       condition: service_completed_successfully
