version: '3.9'

services:
  database:
    extends:
      file: docker-compose.yml
      service: database
    volumes:
      - postgres-data:/var/lib/postgresql/data

  vector:
    extends:
      file: docker-compose.yml
      service: vector

  migrator:
    extends:
      file: docker-compose.yml
      service: migrator
    depends_on:
      - database
    pull_policy: always

  caddy:
    extends:
      file: docker-compose.yml
      service: caddy

  api:
    extends:
      file: docker-compose.yml
      service: api
    depends_on:
      migrator:
        condition: service_completed_successfully
    pull_policy: always

  www:
    extends:
      file: docker-compose.yml
      service: www
    pull_policy: always

  windmill_server:
    extends:
      file: docker-compose-windmill.yml
      service: windmill_server
    depends_on:
      - database

  windmill_worker_native:
    extends:
      file: docker-compose-windmill.yml
      service: windmill_worker_native
    depends_on:
      - database

  windmill_lsp:
    extends:
      file: docker-compose-windmill.yml
      service: windmill_lsp
    volumes:
      - windmill_lsp_cache:/root/.cache

volumes:
  postgres-data:
  windmill_lsp_cache:
