version: '3.9'

services:
  # database:
  #   extends:
  #     file: docker-compose.yml
  #     service: database
  #   container_name: hhai-dev-postgres

  # log:
  #   extends:
  #     file: docker-compose.yml
  #     service: log
  #   container_name: hhai-dev-vector

  # migrator:
  #   extends:
  #     file: docker-compose.yml
  #     service: migrator
  #   container_name: hhai-dev-migrator
  #   depends_on:
  #     - database
  #   pull_policy: always

  caddy:
    extends:
      file: docker-compose.yml
      service: caddy

  # api:
  #   extends:
  #     file: docker-compose.yml
  #     service: api
  #   depends_on:
  #     migrator:
  #       condition: service_completed_successfully
  #   pull_policy: always

  www:
    extends:
      file: docker-compose.yml
      service: www
    pull_policy: always

volumes:
  www-hhai.dev:
  caddy-data:
  caddy-config:
