version: '3.1'

services:
  database:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    container_name: hhai-dev-postgres
    ports:
      - 5432:5432

  log:
    image: timberio/vector:0.31.0-distroless-libc
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
      - /var/run/docker.sock:/var/run/docker.sock

  migrator:
    image: hhai-dev/migrator
    build:
      context: ..
      dockerfile: docker/prisma-migrator.Dockerfile
    env_file:
      - ../.env
