name: hhai.dev-www Docker build & push

on:
  push:
    branches: [ "main" ]
    paths:
      - apps/hhai.dev/**
  workflow_dispatch:

jobs:

  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/wonrax/hhai-dev-www:latest
          file: docker/hhai-dev-www.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy.yml
    needs: build-and-push
    secrets: inherit
