name: Deploy using SSH and Docker Compose

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    name: Run ssh command on host machine
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:wrx-sh-ci

      - name: Run ssh deploy command
        run: |
          ssh -o StrictHostKeyChecking=no root@yorgos "
            podman pull ghcr.io/wonrax/wrx-sh-api:latest \
                        ghcr.io/wonrax/wrx-sh-www:latest \
                        ghcr.io/wonrax/wrx-sh-migrator:latest
            systemctl restart podman-compose-wrx-sh-root.target
          "
