[sources.api]
type = "docker_logs"
include_containers = ["wrx-sh-api"]

    [sources.api.multiline]
    start_pattern = "^[^\\s]"
    mode = "continue_through"
    condition_pattern = "^[\\s]+"
    timeout_ms = 50

[sources.caddy]
type = "docker_logs"
include_containers = ["wrx-sh-caddy"]

    [sources.caddy.multiline]
    start_pattern = "^[^\\s]"
    mode = "continue_through"
    condition_pattern = "^[\\s]+"
    timeout_ms = 50

# [sinks.grafana_loki]
# type = "loki"
# inputs = [ "api" ]
# endpoint = "${GRAFANA_LOKI_URL}"
# encoding.codec = "json"
#
#     [sinks.grafana_loki.labels]
#     env = "${ENVIRONMENT}"
#     domain = "hhai.dev"
#     "container_name" = "{{ container_name }}"
#
#     [sinks.grafana_loki.auth]
#     strategy = "basic"
#     user = "${GRAFANA_LOKI_USER}"
#     password = "${GRAFANA_LOKI_PASSWORD}"

[sinks.new_relic]
type = "new_relic"
inputs = ["api", "caddy"]
account_id = "${NEW_RELIC_ACCOUNT_ID}"
license_key = "${NEW_RELIC_LICENSE_KEY}"
api = "logs"
region = "eu"
